# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.
require(File.join(File.dirname(__FILE__), 'config', 'boot'))
require 'rake'
require 'rake/testtask'
require 'rake/rdoctask'
require 'tasks/rails'
require 'windot'

task :default => :doc
task :xslt => :doc
task :doc => "doc:make_html"

dots=FileList['**/*.dot']
picdir = "public/images/paper"
task :dot => :dotTrans
task :dotTrans do 
  dots.each do |f|
	  png="#{picdir}/#{File.basename(f,'.dot')}.png" 
	  dot2png(f,png)
	end
end
